DROP TABLE RECHNUNG;
DROP TABLE OPENPOST;
DROP TABLE BEITRAG;
DROP TABLE BANKVERBINDUNG;
DROP TABLE ADDRESS;
DROP TABLE CONTACT;
DROP TABLE CV;
DROP INDEX PERSON_IX_FAM;
DROP INDEX PERSON_IX_NAME;
DROP TABLE PERSON;


CREATE TABLE PERSON (
    MGLNR BIGINT PRIMARY KEY,
    FNR INT ,
    FIRMA VARCHAR(128),
    ANREDE VARCHAR(128),
    TITEL VARCHAR(128),
    NACHNAME VARCHAR(128),
    VORNAME VARCHAR(128),
    HAUPTKATEGORIE VARCHAR(128),
    GEBURTSDATUM DATE,
    BEMERKUNG VARCHAR(128),
    STATUS VARCHAR(128),
    EINTRITT DATE,
    AUSTRITT DATE,
    KUENDIGUNG VARCHAR(128),
    ABWEICHENDERZAHLER VARCHAR(128),
    ZAHLUNGSMODUS VARCHAR(128)
);

CREATE INDEX PERSON_IX_FAM ON PERSON (FNR);
CREATE INDEX PERSON_IX_NAME ON PERSON (NACHNAME, FNR, VORNAME);

CREATE TABLE ADDRESS (
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    MGLNR BIGINT,
    STRASSE VARCHAR(128),
    PLZ VARCHAR(16),
    ORT VARCHAR(128),
    LAND VARCHAR(128),
    FOREIGN KEY(MGLNR) REFERENCES PERSON(MGLNR)
);

CREATE TABLE CONTACT (
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    MGLNR BIGINT,
    CONTACTKEY VARCHAR(128),
    CONTACTVALUE VARCHAR(128),
    FOREIGN KEY(MGLNR) REFERENCES PERSON(MGLNR)
);

CREATE TABLE CV (
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    MGLNR BIGINT,
    CVKEY VARCHAR(128),
    CVVALUE VARCHAR(128),
    VALIDFROM DATE,
    VALIDTO DATE,
    FOREIGN KEY(MGLNR) REFERENCES PERSON(MGLNR)
);

CREATE TABLE BANKVERBINDUNG (
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    MGLNR BIGINT,
    FNR INT,
    IBAN VARCHAR(128),
    BIC VARCHAR(128),
    KONTOINHABER VARCHAR(128),
    MANDATSREFERENZ VARCHAR(128),
    MANDAT_VORHANDEN BOOLEAN,
    FOREIGN KEY(MGLNR) REFERENCES PERSON(MGLNR)
);

CREATE TABLE BEITRAG (
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    MGLNR BIGINT,
    FNR INT,
    BEITRAGSPOSITION VARCHAR(128),
    ABRECHNUNGSSTATUS VARCHAR(128),
    ZAHLUNGSWEISE VARCHAR(128),
    FOREIGN KEY(MGLNR) REFERENCES PERSON(MGLNR)
);

CREATE TABLE RECHNUNG (
    MGLNR BIGINT,
    FNR INT,
    RECHNUNGSDATUM DATE,
    RECHNUNGSNUMMER BIGINT PRIMARY KEY,
    RECHNUNGSSUMME INT,
    FOREIGN KEY(MGLNR) REFERENCES PERSON(MGLNR)
);

CREATE TABLE OPENPOST (
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    MGLNR BIGINT,
    SUMMEVORJAHR INT,
    SUMMEAKTJAHR INT,
    FOREIGN KEY(MGLNR) REFERENCES PERSON(MGLNR)
);

