DROP TABLE IDCREMOTE.VEREIN;

CREATE TABLE IDCREMOTE.VEREIN (
    MGLNR BIGINT PRIMARY KEY,
    FIRMA VARCHAR(128),
    STRASSE VARCHAR(128),
    PLZ VARCHAR(16),
    ORT VARCHAR(128),
    LAND VARCHAR(128),
    REGISTER VARCHAR(128),
    EMAIL VARCHAR(128),
    URI VARCHAR(128),
    DATATIME TIMESTAMP
);
