DROP TABLE IDCREMOTE.VEREIN;

CREATE TABLE IDCREMOTE.VEREIN (
    MGLNR BIGINT PRIMARY KEY,
    FIRMA VARCHAR(128),
    STRASSE VARCHAR(128),
    PLZ VARCHAR(16),
    ORT VARCHAR(128),
    LAND VARCHAR(128),
    REGISTER VARCHAR(128),
    EMAIL VARCHAR(128),
    URI VARCHAR(128),
    URIMGV VARCHAR(128),
    PWD VARCHAR(128),
    URIDAV VARCHAR(256),
    DATATIME TIMESTAMP
);

INSERT INTO IDCREMOTE.VEREIN (
  MGLNR,
  FIRMA,
  STRASSE,
  PLZ,
  ORT,
  LAND,
  REGISTER,
  EMAIL,
  URI,
  URIMGV,
  PWD,
  URIDAV,
  DATATIME) 
VALUES (
  0,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'http://null.null',
  'pass@123',
  '',
  '2000-01-01 00:00:00.000');
