DELETE FROM IDCSTAGE.FREMDZAHLER;
DELETE FROM IDCSTAGE.VEREIN;
DELETE FROM IDCSTAGE.RECHNUNGEN;
DELETE FROM IDCSTAGE.BEITRAGSPOSITIONEN;
DELETE FROM IDCSTAGE.LEBENSLAUF;
DELETE FROM IDCSTAGE.OFFENERECHNUNGEN;
DELETE FROM IDCSTAGE.PERSON;