DELETE FROM IDCREMOTE.OFFENERECHNUNGEN;
DELETE FROM IDCREMOTE.ADDRESS;
DELETE FROM IDCREMOTE.CONTACT;
DELETE FROM IDCREMOTE.BANKVERBINDUNG;
DELETE FROM IDCREMOTE.RECHNUNG;
DELETE FROM IDCREMOTE.BEITRAG;
DELETE FROM IDCREMOTE.CV;
DELETE FROM IDCLOCAL.SCANLOG;

DELETE FROM IDCREMOTE.PERSON;

DELETE FROM IDCREMOTE.FAMILY;

INSERT INTO IDCREMOTE.FAMILY (FNR) 
  SELECT DISTINCT FAMILIENNUMMER_SEWOBE AS FNR 
  FROM IDCSTAGE.PERSON
  WHERE FAMILIENNUMMER_SEWOBE IS NOT NULL;

INSERT INTO IDCREMOTE.PERSON (
    MGLNR, 
    FNR, 
    FIRMA, 
    ANREDE, 
    TITEL, 
    NACHNAME,
    VORNAME,
    HAUPTKATEGORIE,
    GEBURTSDATUM,
    BEMERKUNG,
    STATUS, 
    EINTRITT,
    AUSTRITT,
    KUENDIGUNG,
    ABWEICHENDERZAHLER,
    ZAHLUNGSMODUS) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE, 
        FAMILIENNUMMER_SEWOBE,
        FIRMA, 
        ANREDE, 
        TITEL, 
        NACHNAME,
        VORNAME,
        HAUPTKATEGORIE,
        GEBURTSDATUM,
        BEMERKUNG ,
        STATUS,
        EINTRITT,
        AUSTRITT,
        KUENDIGUNG, 
        ABWEICHENDERZAHLER,
        ZAHLUNGSMODUS 
    FROM IDCSTAGE.PERSON;

INSERT INTO IDCREMOTE.ADDRESS (
    MGLNR, 
    STRASSE,
    PLZ,
    ORT,
    LAND) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        STRASSE,
        PLZ,
        ORT,
        LAND
    FROM IDCSTAGE.PERSON;

INSERT INTO IDCREMOTE.CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefon-1',
        TELEFON_1
    FROM IDCSTAGE.PERSON where TELEFON_1 IS NOT NULL;

INSERT INTO IDCREMOTE.CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefon-2',
        TELEFON_2
    FROM IDCSTAGE.PERSON where TELEFON_2 IS NOT NULL;

INSERT INTO IDCREMOTE.CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Mobil',
        MOBIL
    FROM IDCSTAGE.PERSON where MOBIL IS NOT NULL;

INSERT INTO IDCREMOTE.CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefax',
        TELEFAX
    FROM IDCSTAGE.PERSON where TELEFAX IS NOT NULL;

INSERT INTO IDCREMOTE.CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'e-Mail',
        EMAIL
    FROM IDCSTAGE.PERSON where EMAIL IS NOT NULL;

INSERT INTO IDCREMOTE.BANKVERBINDUNG (
    MGLNR,
    FNR,
    IBAN,
    BIC,
    KONTOINHABER,
    MANDATSREFERENZ,
    MANDAT_VORHANDEN)
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE, 
        FAMILIENNUMMER_SEWOBE,
        substr(IBAN,1,4)||'XXXXXXXXXXXXXXX'||substr(IBAN,20) as IBAN,
        BIC,
        KONTOINHABER,
        MANDATSREFERENZ,
        MANDAT_VORHANDEN 
    FROM IDCSTAGE.PERSON 
    WHERE IBAN IS NOT NULL;

INSERT INTO IDCREMOTE.RECHNUNG (
    RECHNUNGSNUMMER,
    MGLNR,
    FNR,
    RECHNUNGSDATUM,
    RECHNUNGSSUMME,
    ZAHLMODUS,
    ZAHLUNGSZIEL)
    SELECT DISTINCT RECHNUNGSNUMMER,
        MITGLIEDSNUMMER_SEWOBE, 
        FAMILIENNUMMER_SEWOBE,
        RECHNUNGSDATUM,
        RECHNUNGSSUMME,
        ZAHLMODUS,
        ZAHLUNGSZIEL 
    FROM IDCSTAGE.RECHNUNGEN 
    WHERE RECHNUNGSNUMMER IS NOT NULL;


INSERT INTO IDCREMOTE.BEITRAG (
    MGLNR,
    FNR,
    BEITRAGSPOSITION,
    BEITRAGSKOMMENTAR,
    FAELLIG_START,
    FAELLIG_ENDE,
    ABRECHNUNGSSTATUS,
    ZAHLUNGSWEISE
    ) SELECT  
        MITGLIEDSNUMMER_SEWOBE AS MGLNR, 
        FAMILIENNUMMER_SEWOBE AS FNR,
        BEITRAGSPOSITION,
        BEITRAGSKOMMENTAR,
        FAELLIG_START,
        FAELLIG_ENDE,
        ABRECHNUNGSSTATUS,
        ZAHLUNGSWEISE
    FROM IDCSTAGE.BEITRAGSPOSITIONEN
    WHERE BEITRAGSPOSITION IS NOT NULL;


INSERT INTO IDCREMOTE.CV (
  MGLNR,
  CVKEY,
  CVVALUE,
  VALIDFROM,
  VALIDTO,
  KURZTEXT,
  LANGTEXT
  ) SELECT
    MITGLIEDSNUMMER_SEWOBE AS MGLNR,
    LEBENSLAUF_ART AS CVKEY,
    LEBENSLAUF_BEZEICHNUNG AS CVVALUE,
    LEBENSLAUF_BEGINN AS VALIDFROM,
    LEBENSLAUF_ENDE AS VALIDTO,
    LEBENSLAUF_KURZTEXT AS KURZTEXT,
    LEBENSLAUF_LANGTEXT AS LANGTEXT
  FROM IDCSTAGE.LEBENSLAUF
  WHERE LEBENSLAUF_BEZEICHNUNG IS NOT NULL;

INSERT INTO IDCREMOTE.OFFENERECHNUNGEN (
    RECHNUNGSNUMMER,
    MGLNR,
    FNR,
    RECHNUNGSDATUM,
    RECHNUNGSSUMME,
    ZAHLMODUS,
    ZAHLUNGSZIEL, 
    MAHNSTUFE)
    SELECT DISTINCT RECHNUNGSNUMMER,
        O.MITGLIEDSNUMMER_SEWOBE AS MGLNR, 
        P.FNR AS FNR,
        O.RECHNUNGSDATUM AS RECHNUNGSDATUM,
        O.AKTUELLOFFEN AS RECHNUNGSSUMME,
        O.ZAHLWEISE AS ZAHLMODUS,
        O.ZAHLUNGSZIEL AS ZAHLUNGSZIEL,
        O.MAHNSTUFE AS MAHNSTUFE
    FROM IDCREMOTE.PERSON P, IDCSTAGE.OFFENERECHNUNGEN O
    WHERE O.RECHNUNGSNUMMER IS NOT NULL
    AND P.MGLNR=O.MITGLIEDSNUMMER_SEWOBE;

UPDATE IDCREMOTE.VEREIN 
  SET  IDCREMOTE.VEREIN.MGLNR = (SELECT IDCSTAGE.VEREIN.VEREINSNR FROM IDCSTAGE.VEREIN),
       IDCREMOTE.VEREIN.FIRMA = (SELECT IDCSTAGE.VEREIN.FIRMA FROM IDCSTAGE.VEREIN),
       IDCREMOTE.VEREIN.STRASSE = (SELECT IDCSTAGE.VEREIN.STRASSE FROM IDCSTAGE.VEREIN),
       IDCREMOTE.VEREIN.PLZ = (SELECT IDCSTAGE.VEREIN.PLZ FROM IDCSTAGE.VEREIN),
       IDCREMOTE.VEREIN.ORT = (SELECT IDCSTAGE.VEREIN.ORT FROM IDCSTAGE.VEREIN),
       IDCREMOTE.VEREIN.LAND = (SELECT IDCSTAGE.VEREIN.LAND FROM IDCSTAGE.VEREIN),
       IDCREMOTE.VEREIN.REGISTER = (SELECT IDCSTAGE.VEREIN.REGISTER FROM IDCSTAGE.VEREIN),
       IDCREMOTE.VEREIN.EMAIL = (SELECT IDCSTAGE.VEREIN.EMAIL FROM IDCSTAGE.VEREIN),
       IDCREMOTE.VEREIN.URI = (SELECT IDCSTAGE.VEREIN.URI FROM IDCSTAGE.VEREIN)
WHERE EXISTS (SELECT * FROM IDCSTAGE.VEREIN);

UPDATE IDCREMOTE.VEREIN 
  SET  IDCREMOTE.VEREIN.DATATIME =CURRENT_TIMESTAMP;

UPDATE IDCREMOTE.PERSON 
SET IDCREMOTE.PERSON.FREMDZAHLER=(SELECT IDCSTAGE.FREMDZAHLER.MITGLIEDSNUMMER_FREMDZAHLER FROM IDCSTAGE.FREMDZAHLER WHERE IDCSTAGE.FREMDZAHLER.MITGLIEDSNUMMER_SEWOBE=IDCREMOTE.PERSON.MGLNR)
WHERE EXISTS (SELECT * FROM IDCSTAGE.FREMDZAHLER WHERE IDCSTAGE.FREMDZAHLER.MITGLIEDSNUMMER_SEWOBE=IDCREMOTE.PERSON.MGLNR);