DELETE FROM OFFENERECHNUNGEN;
DELETE FROM ADDRESS;
DELETE FROM CONTACT;
DELETE FROM BANKVERBINDUNG;
DELETE FROM RECHNUNG;
DELETE FROM BEITRAG;
DELETE FROM CV;
DELETE FROM OFFENERECHNUNGEN;
DELETE FROM SCANLOG;

DELETE FROM PERSON;

DELETE FROM FAMILY;

INSERT INTO FAMILY (FNR) 
  SELECT DISTINCT FAMILIENNUMMER_SEWOBE AS FNR 
  FROM STAGE.PERSON
  WHERE FAMILIENNUMMER_SEWOBE IS NOT NULL;

INSERT INTO PERSON (
    MGLNR, 
    FNR, 
    FIRMA, 
    ANREDE, 
    TITEL, 
    NACHNAME,
    VORNAME,
    HAUPTKATEGORIE,
    GEBURTSDATUM,
    BEMERKUNG,
    STATUS, 
    EINTRITT,
    AUSTRITT,
    KUENDIGUNG,
    ABWEICHENDERZAHLER,
    ZAHLUNGSMODUS) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE, 
        FAMILIENNUMMER_SEWOBE,
        FIRMA, 
        ANREDE, 
        TITEL, 
        NACHNAME,
        VORNAME,
        HAUPTKATEGORIE,
        GEBURTSDATUM,
        BEMERKUNG ,
        STATUS,
        EINTRITT,
        AUSTRITT,
        KUENDIGUNG, 
        ABWEICHENDERZAHLER,
        ZAHLUNGSMODUS 
    FROM STAGE.PERSON;

INSERT INTO ADDRESS (
    MGLNR, 
    STRASSE,
    PLZ,
    ORT,
    LAND) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        STRASSE,
        PLZ,
        ORT,
        LAND
    FROM STAGE.PERSON;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefon-1',
        TELEFON_1
    FROM STAGE.PERSON where TELEFON_1 IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefon-2',
        TELEFON_2
    FROM STAGE.PERSON where TELEFON_2 IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Mobil',
        MOBIL
    FROM STAGE.PERSON where MOBIL IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefax',
        TELEFAX
    FROM STAGE.PERSON where TELEFAX IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'e-Mail',
        EMAIL
    FROM STAGE.PERSON where EMAIL IS NOT NULL;

INSERT INTO BANKVERBINDUNG (
    MGLNR,
    FNR,
    IBAN,
    BIC,
    KONTOINHABER,
    MANDATSREFERENZ,
    MANDAT_VORHANDEN)
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE, 
        FAMILIENNUMMER_SEWOBE,
        substr(IBAN,1,4)||'XXXXXXXXXXXXXXX'||substr(IBAN,20) as IBAN,
        BIC,
        KONTOINHABER,
        MANDATSREFERENZ,
        MANDAT_VORHANDEN 
    FROM STAGE.PERSON 
    WHERE IBAN IS NOT NULL;

INSERT INTO RECHNUNG (
    RECHNUNGSNUMMER,
    MGLNR,
    FNR,
    RECHNUNGSDATUM,
    RECHNUNGSSUMME,
    ZAHLMODUS,
    ZAHLUNGSZIEL)
    SELECT DISTINCT RECHNUNGSNUMMER,
        MITGLIEDSNUMMER_SEWOBE, 
        FAMILIENNUMMER_SEWOBE,
        RECHNUNGSDATUM,
        RECHNUNGSSUMME,
        ZAHLMODUS,
        ZAHLUNGSZIEL 
    FROM STAGE.RECHNUNGEN 
    WHERE RECHNUNGSNUMMER IS NOT NULL;


INSERT INTO BEITRAG (
    MGLNR,
    FNR,
    BEITRAGSPOSITION,
    BEITRAGSKOMMENTAR,
    FAELLIG_START,
    FAELLIG_ENDE,
    ABRECHNUNGSSTATUS,
    ZAHLUNGSWEISE
    ) SELECT  
        MITGLIEDSNUMMER_SEWOBE AS MGLNR, 
        FAMILIENNUMMER_SEWOBE AS FNR,
        BEITRAGSPOSITION,
        BEITRAGSKOMMENTAR,
        FAELLIG_START,
        FAELLIG_ENDE,
        ABRECHNUNGSSTATUS,
        ZAHLUNGSWEISE
    FROM STAGE.BEITRAGSPOSITIONEN
    WHERE BEITRAGSPOSITION IS NOT NULL;


INSERT INTO CV (
  MGLNR,
  CVKEY,
  CVVALUE,
  VALIDFROM,
  VALIDTO,
  KURZTEXT,
  LANGTEXT
  ) SELECT
    MITGLIEDSNUMMER_SEWOBE AS MGLNR,
    LEBENSLAUF_ART AS CVKEY,
    LEBENSLAUF_BEZEICHNUNG AS CVVALUE,
    LEBENSLAUF_BEGINN AS VALIDFROM,
    LEBENSLAUF_ENDE AS VALIDTO,
    LEBENSLAUF_KURZTEXT AS KURZTEXT,
    LEBENSLAUF_LANGTEXT AS LANGTEXT
  FROM STAGE.LEBENSLAUF
  WHERE LEBENSLAUF_BEZEICHNUNG IS NOT NULL;

INSERT INTO OFFENERECHNUNGEN (
    RECHNUNGSNUMMER,
    MGLNR,
    FNR,
    RECHNUNGSDATUM,
    RECHNUNGSSUMME,
    ZAHLMODUS,
    ZAHLUNGSZIEL, 
    MAHNSTUFE)
    SELECT DISTINCT RECHNUNGSNUMMER,
        O.MITGLIEDSNUMMER_SEWOBE AS MGLNR, 
        P.FNR AS FNR,
        O.RECHNUNGSDATUM AS RECHNUNGSDATUM,
        O.AKTUELLOFFEN AS RECHNUNGSSUMME,
        O.ZAHLWEISE AS ZAHLMODUS,
        O.ZAHLUNGSZIEL AS ZAHLUNGSZIEL,
        O.MAHNSTUFE AS MAHNSTUFE
    FROM PERSON P, STAGE.OFFENERECHNUNGEN O
    WHERE O.RECHNUNGSNUMMER IS NOT NULL
    AND P.MGLNR=O.MITGLIEDSNUMMER_SEWOBE;