DELETE FROM OFFENERECHNUNGEN;
DELETE FROM ADDRESS;
DELETE FROM CONTACT;
DELETE FROM BANKVERBINDUNG;
DELETE FROM RECHNUNG;
DELETE FROM BEITRAG;
DELETE FROM OPENPOST;
DELETE FROM CV;
DELETE FROM OFFENERECHNUNGEN;

DELETE FROM PERSON;

INSERT INTO PERSON (
    MGLNR, 
    FNR, 
    FIRMA, 
    ANREDE, 
    TITEL, 
    NACHNAME,
    VORNAME,
    HAUPTKATEGORIE,
    GEBURTSDATUM,
    BEMERKUNG,
    STATUS, 
    EINTRITT,
    AUSTRITT,
    KUENDIGUNG,
    ABWEICHENDERZAHLER,
    ZAHLUNGSMODUS) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE, 
        FAMILIENNUMMER_SEWOBE,
        FIRMA, 
        ANREDE, 
        TITEL, 
        NACHNAME,
        VORNAME,
        HAUPTKATEGORIE,
        GEBURTSDATUM,
        BEMERKUNG ,
        STATUS,
        EINTRITT,
        AUSTRITT,
        KUENDIGUNG, 
        ABWEICHENDERZAHLER,
        ZAHLUNGSMODUS 
    FROM DLRG.PERSON_STAGE;

INSERT INTO ADDRESS (
    MGLNR, 
    STRASSE,
    PLZ,
    ORT,
    LAND) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        STRASSE,
        PLZ,
        ORT,
        LAND
    FROM DLRG.PERSON_STAGE;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefon-1',
        TELEFON_1
    FROM DLRG.PERSON_STAGE where TELEFON_1 IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefon-2',
        TELEFON_2
    FROM DLRG.PERSON_STAGE where TELEFON_2 IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Mobil',
        MOBIL
    FROM DLRG.PERSON_STAGE where MOBIL IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefax',
        TELEFAX
    FROM DLRG.PERSON_STAGE where TELEFAX IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'e-Mail',
        EMAIL
    FROM DLRG.PERSON_STAGE where EMAIL IS NOT NULL;

INSERT INTO BANKVERBINDUNG (
    MGLNR,
    FNR,
    IBAN,
    BIC,
    KONTOINHABER,
    MANDATSREFERENZ,
    MANDAT_VORHANDEN)
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE, 
        FAMILIENNUMMER_SEWOBE,
        IBAN,
        BIC,
        KONTOINHABER,
        MANDATSREFERENZ,
        MANDAT_VORHANDEN 
    FROM PERSON_STAGE 
    WHERE IBAN IS NOT NULL;

INSERT INTO RECHNUNG (
    RECHNUNGSNUMMER,
    MGLNR,
    FNR,
    RECHNUNGSDATUM,
    RECHNUNGSSUMME,
    ZAHLMODUS,
    ZAHLUNGSZIEL)
    SELECT DISTINCT RECHNUNGSNUMMER,
        MITGLIEDSNUMMER_SEWOBE, 
        FAMILIENNUMMER_SEWOBE,
        RECHNUNGSDATUM,
        RECHNUNGSSUMME,
        ZAHLMODUS,
        ZAHLUNGSZIEL 
    FROM RECHNUNGEN_STAGE 
    WHERE RECHNUNGSNUMMER IS NOT NULL;


INSERT INTO BEITRAG (
    MGLNR,
    FNR,
    BEITRAGSPOSITION,
    BEITRAGSKOMMENTAR,
    FAELLIG_START,
    FAELLIG_ENDE,
    ABRECHNUNGSSTATUS,
    ZAHLUNGSWEISE
    ) SELECT  
        MITGLIEDSNUMMER_SEWOBE AS MGLNR, 
        FAMILIENNUMMER_SEWOBE AS FNR,
        BEITRAGSPOSITION,
        BEITRAGSKOMMENTAR,
        FAELLIG_START,
        FAELLIG_ENDE,
        ABRECHNUNGSSTATUS,
        ZAHLUNGSWEISE
    FROM BEITRAGSPOSITIONEN_STAGE
    WHERE BEITRAGSPOSITION IS NOT NULL;

INSERT INTO OPENPOST (
    MGLNR, 
    SUMMEVORJAHR,
    SUMMEAKTJAHR) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE, 
        0,
        0 
    FROM DLRG.PERSON_STAGE;

INSERT INTO CV (
  MGLNR,
  CVKEY,
  CVVALUE,
  VALIDFROM,
  VALIDTO,
  KURZTEXT,
  LANGTEXT
  ) SELECT
    MITGLIEDSNUMMER_SEWOBE AS MGLNR,
    LEBENSLAUF_ART AS CVKEY,
    LEBENSLAUF_BEZEICHNUNG AS CVVALUE,
    LEBENSLAUF_BEGINN AS VALIDFROM,
    LEBENSLAUF_ENDE AS VALIDTO,
    LEBENSLAUF_KURZTEXT AS KURZTEXT,
    LEBENSLAUF_LANGTEXT AS LANGTEXT
  FROM LEBENSLAUF_STAGE
  WHERE LEBENSLAUF_BEZEICHNUNG IS NOT NULL;

INSERT INTO OFFENERECHNUNGEN (
    RECHNUNGSNUMMER,
    MGLNR,
    RECHNUNGSDATUM,
    RECHNUNGSSUMME,
    ZAHLMODUS,
    ZAHLUNGSZIEL, 
    MAHNSTUFE)
    SELECT DISTINCT RECHNUNGSNUMMER,
        MITGLIEDSNUMMER_SEWOBE AS MGLNR, 
        RECHNUNGSDATUM,
        AKTUELLOFFEN AS RECHNUNGSSUMME,
        ZAHLWEISE AS ZAHLMODUS,
        ZAHLUNGSZIEL,
        MAHNSTUFE 
    FROM OFFENERECHNUNGEN_STAGE
    WHERE RECHNUNGSNUMMER IS NOT NULL;