INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefon-1',
        TELEFON_1
    FROM DLRG.PERSON_STAGE where TELEFON_1 IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefon-2',
        TELEFON_2
    FROM DLRG.PERSON_STAGE where TELEFON_2 IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Mobil',
        MOBIL
    FROM DLRG.PERSON_STAGE where MOBIL IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'Telefax',
        TELEFAX
    FROM DLRG.PERSON_STAGE where TELEFAX IS NOT NULL;

INSERT INTO CONTACT (
    MGLNR, 
    CONTACTKEY,
    CONTACTVALUE) 
    SELECT DISTINCT 
        MITGLIEDSNUMMER_SEWOBE,
        'e-Mail',
        EMAIL
    FROM DLRG.PERSON_STAGE where EMAIL IS NOT NULL;