drop table person_stage;
create table person_stage (
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
nummer int,
mitgliedsnummer_sewobe bigint,
familiennummer_sewobe int,
firma varchar(128),
anrede varchar(128),
titel varchar(128),
nachname varchar(128),
vorname varchar(128),
strasse varchar(128),
plz varchar(16),
ort varchar(128),
land varchar(128),
hauptkategorie varchar(128),
telefon_1 varchar(128),
telefon_2 varchar(128),
mobil varchar(128),
telefax varchar(128),
email varchar(128),
geburtsdatum date,
bemerkung varchar(128),
status varchar(128),
eintritt date,
austritt date,
kuendigung date,
iban varchar(128),
bic varchar(128),
kontoinhaber varchar(128),
mandatsreferenz varchar(128),
mandat_vorhanden boolean,
abweichenderzahler boolean,
beitragsposition varchar(128),
beitragskommentar varchar(128),
faellig_start date,
faellig_ende date,
abrechnungsstatus varchar(128),
zahlungsmodus varchar(128),
zahlungsweise varchar(128),
offene_beitraege int,
alter_errechnet int,
rechnungsdatum date,
rechnungsnummer bigint,
rechnungssumme int
);
